config/routes.rb
DoWorkSon::Application.routes.draw do
  get 'text/receivedtext'
  resources :chores
  
  root :to => "page#home"
  match "video" => "page#video"
  match "crack" => "text#remind"
  

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  belongs_to :currentPerson, :class_name => "Person"
  has_many :people, :dependent => :destroy
  accepts_nested_attributes_for :people, allow_destroy: true
  attr_accessible :currentPerson,:people_attributes,:time_reminded,:time_completed, :description, :friday, :monday, :name, :saturday, :start_date, :sunday, :thursday, :time, :tuesday, :wednesday
  
  validates :name, :length => { :maximum =>30 }
  validate :one_day_must_be_set
  validate :at_least_a_person

  after_initialize :init

    def init
      t= Time.now
      self.time_completed  ||= t -1.day
      self.time_reminded ||= t - 1.day
      self.currentPerson = self.people.first
      count =0
      self.people.each do |p|
          p.ordering_number = count
          count += -1
      end
    end
  
 
    def at_least_a_person
        if people.empty?
            errors.add(:base, "Gotta have someone doing the chores")
        end
    end
    def one_day_must_be_set
        unless monday || tuesday || wednesday || thursday || friday || saturday || sunday
            errors.add(:base, "Sup with not setting a day of the week, bro?")
        end
    end

  
  def opt_out_current
      #remove current person and set chore to next person
      person = self.currentPerson
      self.update_shift
      person.destroy
      if self.people.empty?
          self.destroy
      end
  end
  
  def next_people
      list = self.people.order(:ordering_number)
      list.each_index do |i|

          if list[i].id == self.currentPerson.id
              return list if i==0
              return list[i..-1] + list[0..(i-1)]
              
          end
      end
  end
  
  def update_shift
      list = self.people.order(:ordering_number)
      n=false
      list.each do |p|
          if n
              self.currentPerson = p
              self.save
              return 
          end
          if p.id == self.currentPerson.id
              n =true
          end
      end
      self.currentPerson = list.first
      self.save
  end
  
  def self.find_chores  
      t= Time.now
      day = t.strftime('%A').downcase
      hours_ago = t - 12.hours
      pre_time = Time.gm(2000,1,1,0,0,0) + t.hour.hours + t.min.minutes + t.sec.seconds + 1.hour
      pre_time = Time.gm(2000,1,1,0,0,0) if pre_time<Time.gm(2000,1,1,0,0,1)
      chores = Chore.where(day+" AND (time_completed IS NULL OR time_completed < ?) AND start_date >= ?",hours_ago,t-1.day)
  end
                      
  def self.find_lazy_chores
      t= Time.now
      day = t.strftime('%A').downcase
      hours_ago = t - 12.hours
      pre_time = Time.gm(2000,1,1,0,0,0) + t.min.minutes + t.sec.seconds + 3.hour
      pre_time = Time.gm(2000,1,1,0,0,0) if pre_time<Time.gm(2000,1,1,0,0,1)
      chores = Chore.where(day+" AND (time_completed IS NULL OR time_completed > ?) and time < ? AND start_date >= ?",hours_ago+ 23.hours,pre_time,t-1.day)
  end

end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chores }
    end
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
    @chore = Chore.find(params[:id])
    @daynames = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
    @people = {"monday" => nil,
               "tuesday" => nil,
               "wednesday" => nil,
               "thursday" => nil,
               "friday" => nil,
               "saturday" => nil,
               "sunday" => nil,
               }
    today = Time.now.strftime('%A').downcase
    flag = false
    nextp=@chore.next_people
    @count=today
    while nextp.size < 7 do
        nextp= nextp + nextp
    end
    @people.each do |weekday,v|

        flag = true if weekday.eql? today
        if flag && @chore[weekday]
            @people[weekday]=nextp.shift
        end
    end
    @people.each do |weekday,v|
        flag = false if weekday.eql? today
        if flag && @chore[weekday]
            @people[weekday]=nextp.shift
        end
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/new
  # GET /chores/new.json
  def new
    @chore = Chore.new
    @chore.people.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/1/edit
  def edit
    @chore = Chore.find(params[:id])
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(params[:chore])

    respond_to do |format|
      if @chore.save
        format.html { redirect_to video_path, notice: 'Chore was successfully created.',location: @chore }
        format.json { render json: @chore, status: :created, location: @chore }
      else
        format.html { render action: "new" }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chores/1
  # PUT /chores/1.json
  def update
    @chore = Chore.find(params[:id])

    respond_to do |format|
      if @chore.update_attributes(params[:chore])
        format.html { redirect_to video_path,  notice: 'Chore was successfully updated.',location: @chore }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore = Chore.find(params[:id])
    @chore.destroy

    respond_to do |format|
      format.html { redirect_to chores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_form.html.erb
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<script>
$(function() {
  /*$("#days_of_week").find("input:checkbox").each(function() {
    if($(this).is(':checked')) {
      $("."+$(this).attr("id")).css('background-color', 'greenyellow'); 
    }
  });*/
  updateColors();
  $("#days_of_week button").attr("href", "#");
  
  $("#days_of_week button").click(function() {
    var checkbox = $("#"+$(this).attr("class"));
    checkbox.click();
    updateColors();
    return false;
  });

  function updateColors() {
    $("#days_of_week").find("input:checkbox").each(function() {
      if($(this).is(':checked')) {
        $("."+$(this).attr("id")).css('background-color', 'greenyellow'); 
      } else {
        $("."+$(this).attr("id")).css('background-color', 'white'); 
      }
    });
  }

});
</script>

<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-horizontal"> 
  
    <div class="control-group">  
      <label class="control-label strong" for="name">Chore Name</label>  
      <div class="controls">  
        <%= f.text_field :name, :class => "span3" %>
        <span class="help-block">Examples: Take out the Trash, Sweep the Floor, Pay the Bills, etc.</span>
      </div>  
    </div>  
    <div class="control-group">
      <label class="control-label strong" for="description">Description</label>
      <div class="controls">
        <%= f.text_area :description, {:class => "span3", :rows => "4"} %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label strong" for="notify_time">Start Date</label>
      <div class="controls">
        <%= f.date_select :start_date %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label strong" for="notify_time">Time of Reminder</label>
      <div class="controls">
        <%= f.time_select :time %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label strong" for="days_of_week">Days of the Week</label>
      <div class="controls">
        <table class="table" id="days_of_week">
          <thead>
            <tr>
              <td><button class="chore_sunday">Sunday</button></td>
              <td><button class="chore_monday">Monday</button></td>
              <td><button class="chore_tuesday">Tuesday</button></td>
              <td><button class="chore_wednesday">Wednesday</button></td>
              <td><button class="chore_thursday">Thursday</button></td>
              <td><button class="chore_friday">Friday</button></td>
              <td><button class="chore_saturday">Saturday</button></td>
            </tr>
          </thead>
          <tbody style="display:none">
            <tr>
              <td><%= f.check_box :sunday %></td>
              <td><%= f.check_box :monday %></td>
              <td><%= f.check_box :tuesday %></td>
              <td><%= f.check_box :wednesday %></td>
              <td><%= f.check_box :thursday %></td>
              <td><%= f.check_box :friday %></td>
              <td><%= f.check_box :saturday %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label strong">People</label>
      <div class="controls">
        <div class="people">
          <div class="items">
          <%= f.nested_fields_for :people do |f| %>
            <fieldset class="item">
              Name:
              <%= f.text_field :name %>
              Email:
              <%= f.text_field :email %>
              Phone:
              <%= f.text_field :phone %>

              <a href="#" class="remove"><i class="icon-remove-sign"></i>remove</a>
              <%= f.hidden_field :id %>
              <%= f.hidden_field :_destroy %>
            </fieldset>
          <% end %>
          </div>
          <a href="#" class="add"><i class="icon-plus-sign"></i>add people</a>
        </div>

      </div>
    </div>
  </div>
  <br/><br/>
  <div class="actions center" style="width:200px">
    <%= f.submit :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1 class="west center new_chores_title">Editing chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Chore</th>
      <th>Last Completed</th>
      <th>Next Victim</th>
    </tr>
  </thead>
  <tbody>
<% @chores.each do |chore| %>
  <tr>
    <td>
      <%= link_to "<i class='icon-edit'></i>".html_safe+chore.name, chore %>
      <span class="help-block"><%= chore.description %></span>
    </td>
    <td><span title="<%= chore.time_completed %>"><%=chore.time_completed > Time.now-5.years ? time_ago_in_words(chore.time_completed) : "Never" %></span></td>
    <td><%= chore.currentPerson.name %></td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/chores/new.html.erb
<h1 class="west center new_chores_title">Gettin' Something Done</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>
  <h1 class="west chore_title"><%= @chore.name %></h1>
  <span class="chore_desc"><%= @chore.description %></span>
<br/>
<div class="container">
  <div class="row schedule">
    <div class="span1"></div>
    <div class="span1 day note">
      <div class="top">
        <%= @daynames[Date.today.wday].capitalize %>
        <div class="day_num"><%= Date.today.strftime("%d") %></div>
      </div>
      <div class="bottom">
        <%= @people[@daynames[Date.today.wday]].name if @people[@daynames[Date.today.wday]] %>
      </div>
    </div>
    <div class="span1 day">
      <div class="top">
        <%= @daynames[Date.today.tomorrow.wday%7].capitalize %>
        <div class="day_num"><%= Date.today.tomorrow.strftime("%d") %></div>
      </div>
      <div class="bottom">
        <%= @people[@daynames[Date.today.tomorrow.wday]].name if @people[@daynames[Date.today.tomorrow.wday]] %>
      </div>
    </div>
    <div class="span1 day">
      <div class="top">
        <%= @daynames[Date.today.tomorrow.tomorrow.wday%7].capitalize %>
        <div class="day_num"><%= Date.today.tomorrow.tomorrow.strftime("%d") %></div>
      </div>
      <div class="bottom">
        <%= @people[@daynames[Date.today.tomorrow.tomorrow.wday]].name if @people[@daynames[Date.today.tomorrow.tomorrow.wday]] %>
      </div>
    </div>
    <div class="span1 day">
      <div class="top">
        <%= @daynames[Date.today.tomorrow.tomorrow.tomorrow.wday%7].capitalize %>
        <div class="day_num"><%= Date.today.tomorrow.tomorrow.tomorrow.strftime("%d") %></div>
      </div>
      <div class="bottom">
        <%= @people[@daynames[Date.today.tomorrow.tomorrow.tomorrow.wday]].name if @people[@daynames[Date.today.tomorrow.tomorrow.tomorrow.wday]] %>
      </div>
    </div>
    <div class="span1 day">
      <div class="top">
        <%= @daynames[Date.today.tomorrow.tomorrow.tomorrow.tomorrow.wday%7].capitalize %>
        <div class="day_num"><%= Date.today.tomorrow.tomorrow.tomorrow.tomorrow.strftime("%d") %></div>
      </div>
      <div class="bottom">
        <%= @people[@daynames[Date.today.tomorrow.tomorrow.tomorrow.tomorrow.wday]].name if @people[@daynames[Date.today.tomorrow.tomorrow.tomorrow.tomorrow.wday]]%>
      </div>
    </div>
    <div class="span1 day">
      <div class="top">
        <%= @daynames[Date.today.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.wday%7].capitalize %>
        <div class="day_num"><%= Date.today.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.strftime("%d") %></div>
      </div>
      <div class="bottom">
        <%= @people[@daynames[Date.today.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.wday]].name if @people[@daynames[Date.today.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.wday]] %>
      </div>
    </div>
    <div class="span1 day">
      <div class="top">
        <%= @daynames[Date.today.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.wday%7].capitalize %>
        <div class="day_num"><%= Date.today.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.strftime("%d") %></div>
      </div>
      <div class="bottom">
        <%= @people[@daynames[Date.today.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.wday]].name if @people[@daynames[Date.today.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.tomorrow.wday]] %>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Delete', @chore, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', chores_path %>

app/views/chores/view.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Time</th>
    <th>Startdate</th>
    <th>Monday</th>
    <th>Tuesday</th>
    <th>Wednesday</th>
    <th>Thursday</th>
    <th>Friday</th>
    <th>Saturday</th>
    <th>Sunday</th>
    <th>Currentperson</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chores.each do |chore| %>
  <tr>
    <td><%= chore.name %></td>
    <td><%= chore.time %></td>
    <td><%= chore.startDate %></td>
    <td><%= chore.monday %></td>
    <td><%= chore.tuesday %></td>
    <td><%= chore.wednesday %></td>
    <td><%= chore.thursday %></td>
    <td><%= chore.friday %></td>
    <td><%= chore.saturday %></td>
    <td><%= chore.sunday %></td>
    <td><%= chore.currentPerson %></td>
    <td><%= chore.description %></td>
    <td><%= link_to 'Show', chore %></td>
    <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
    <td><%= link_to 'Destroy', chore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />